name = "nuxt-tiptap"
compatibility_date = "2024-09-19"
main = "./.output/server/index.mjs"
assets = { directory = "./.output/public/" }
durable_objects.bindings = [{ name = "$DurableObject", class_name = "$DurableObject" }]
migrations = [{ tag = "v1", new_classes = ["$DurableObject"] }]
observability = { enabled = true, head_sampling_rate = 1 }
